#!/bin/bash
#$ -S /bin/bash
#$ -cwd
#$ -j y
#$ -pe orte 8

POLE=30
THREAD=8
EXEC=$PBSAMHOME/working_code/PBSAM_all/bin/pbsam_30

MOLDIR=$PBSAMHOME/working_code/PBSAM_all/test/1BRS

SALT_CONC=0.05

PQRFILE="$MOLDIR"/config/1BRS_chainA_p1.5d3_s5i1.pqr

IMATPATH="$MOLDIR/DATA_s5i1/makeIMat/IMAT_P30_250k/chainA"
EXPNAME=1BRS_A_s5i1_i"$SALT_CONC"_p"$POLE"

LOGFILE=selfpol_"$EXPNAME".log
$EXEC spol $THREAD $SALT_CONC  $PQRFILE $IMATPATH $EXPNAME> $LOGFILE 2>&1 


