#!/bin/bash
#$ -S /bin/bash
#$ -cwd
#$ -o selfpol.out
#$ -j y
#$ -pe orte 20

POLE=20
THREAD=20
EXEC=$PBSAMHOME/working_code/PBSAM_all/bin/pbsam_20

MOLDIR=$PBSAMHOME/working_code/PBSAM_all/test/1BRS
SALT_CONC=0.05
PQRFILE="$MOLDIR"/config/1BRS_chainD_p1.5d3_s5i1.pqr

IMATPATH="$MOLDIR/DATA_s5i1/makeIMat/IMAT_P20_250K/chainD"
EXPNAME=1BRS_D_s5i1_i"$SALT_CONC"_p"$POLE"

LOGFILE=selfpol_"$EXPNAME".log
$EXEC spol $THREAD $SALT_CONC  $PQRFILE $IMATPATH $EXPNAME> $LOGFILE 2>&1 


