#!/bin/bash
#$ -S /bin/bash
#$ -cwd
#$ -j y
#$ -pe orte 8

export OMP_NUM_THREADS=8

POLE=30
THREAD=8
EXEC=$PBSAMHOME/BD_tobeparallel/CODE_PBSAM/bin/pbsam

MOLDIR=$PBSAMHOME/Example_1BRS

SALT_CONC=0.05

PQRFILE="$MOLDIR"/config/1BRS_chainD_p1.5d3_s5i1.pqr

IMATPATH="$MOLDIR/DATA_s5i1/makeIMat/IMAT_P30_250k/chainD"
EXPNAME=1BRS_D_s5i1_i"$SALT_CONC"_p"$POLE"

LOGFILE=selfpol_"$EXPNAME".log
$EXEC spol $THREAD $SALT_CONC  $PQRFILE $IMATPATH $EXPNAME> $LOGFILE 2>&1 


